### ISSUE TITLE
Not able to use fdsnws

### ISSUE THREAD

**Issue by maratumba** [eost/docker-seiscomp3#2]
I clone and build the docker container by:
```
git clone https://github.com/eost/docker-seiscomp3.git
cd 2016.333
docker build -t seiscomp3 .
docker run -it --name sc3 -p 8080:8080 --entrypoint=/bin/bash seiscomp3
```
I am running it on a ubuntu machine. seiscomp starts fine but I can't seem to able to use `fdsnws`. Would be great if I could, I failed when I tried to create a seiscomp container by myself.

**Comment by Brtle** [comment]
I just pushed a dockerfile for the last seiscomp3 version (2017.124.02). There was indeed some missing dependencies for the `fdsnws` plugin.

However, the `fdsnws` plugin needs some configuration. Maybe you can try to create a small dockerfile like this:

```
FROM seiscomp3:2017.124.02

COPY scmaster.cfg $INSTALL_DIR/etc/
COPY fdsnws.cfg $INSTALL_DIR/etc/

EXPOSE 8080

ENTRYPOINT seiscomp start && seiscomp exec fdsnws --debug
```

and make sure to correctly configure the database in the `scmaster.cfg` and `fdsnws.cfg` files. The `scmaster.cfg` should look like this:

```
plugins = dbplugin
core.plugins = dbpostgresql
plugins.dbPlugin.dbDriver = postgresql
plugins.dbPlugin.readConnection = user:password@hostname/dbname
plugins.dbPlugin.writeConnection = user:password@hostname/dbname
```

and the `fdsnws.cfg`:

```
logging.level = 4
database.type = postgresql
database.parameters = user:password@hostname/dbname
connections = 100
serveDataSelect = false
```

This way, your FDSN webservice should be running.

**Comment by maratumba** [comment]
Will try this. Thanks for the quick reply!
