### ISSUE TITLE
QuakeML to SC3ML

### ISSUE THREAD

**Issue by maratumba** [eost/docker-seiscomp3#3]
Kind of unrelated but I saw your post that mentions an [xslt converter](http://stackissue.com/obspy/obspy/add-sc3ml-event-write-support-1638.html) that I urgently need but I couldn't find it in your repo. I'd be grateful if you could point me to it.

**Comment by Brtle** [comment]
You can find this file both on the [ObsPy repository](https://github.com/obspy/obspy/tree/master/obspy/io/seiscomp/data) or on the [upstream website](http://geofon.gfz-potsdam.de/schema/). A SC3ML module using this file is ready on the ObsPy master branch and should be released in the next version (1.1.0).
